/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { TheAmazingTozziDuckMachine__factory } from "./TheAmazingTozziDuckMachine__factory";
